classdef TestErode
    %TestErode
    properties (Constant)
        img = uint8([...
            0 0 0 0 0 0 0 0 0 0;...
            0 0 0 0 0 0 0 0 0 0;...
            0 0 0 0 0 0 0 0 0 0;...
            0 0 0 1 1 1 0 0 0 0;...
            0 0 0 1 1 1 0 0 0 0;...
            0 0 0 1 1 1 0 0 0 0;...
            0 0 0 0 0 0 0 0 0 0;...
            0 0 0 0 0 0 0 0 0 0;...
            0 0 0 0 0 0 0 0 0 0;...
            0 0 0 0 0 0 0 0 0 0;...
        ]);
    end

    methods (Static)
        function test_1
            result = cv.erode(TestErode.img);
            validateattributes(result, {class(TestErode.img)}, ...
                {'size',size(TestErode.img)});
        end

        function test_2
            result = cv.erode(TestErode.img, 'Element',ones(3), ...
                'Anchor',[0,1], 'Iterations',1, 'BorderType','Constant');
            validateattributes(result, {class(TestErode.img)}, ...
                {'size',size(TestErode.img)});
        end

        function test_error_1
            try
                cv.erode();
                throw('UnitTest:Fail');
            catch e
                assert(strcmp(e.identifier,'mexopencv:error'));
            end
        end
    end

end
